apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.fullname" . }}-postgres-secrets
  labels:
    {{- include "db.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{  b64enc .Values.db.envVars.POSTGRES_PASSWORD  }}
