apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.svc.headless" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: port1
      port: {{ .Values.db.service.ports.port1.port }}
      targetPort: {{ .Values.db.service.ports.port1.targetPort }}
      protocol: {{ .Values.db.service.ports.port1.protocol }}
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}