apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "db.fullname" . }}-headless
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db.labels" . | nindent 8 }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.db.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: db
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: port1
              containerPort: {{ .Values.db.service.ports.port1.containerPort }}
              protocol: {{ .Values.db.service.ports.port1.protocol }}
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.envVars.POSTGRES_USER | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.envVars.POSTGRES_DB | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "db.fullname" . }}-postgres-secrets
                  key: postgres-password
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/05_external_services.sql
              subPath: 05_external_services.sql
            {{- if .Values.db.persistence.enabled }}
            - name: data
              mountPath: /var/lib/postgresql/data
            {{- end }}
      volumes:
        - name: initdb
          configMap:
            name: {{ include "db.fullname" . }}-initdb-script
  {{- if and .Values.db.persistence.enabled .Values.db.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.db.persistence.existingClaim $ }}
  {{- else if not .Values.db.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        {{- range .Values.db.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.db.persistence.size | quote }}
  {{- end }}
