apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.enablerNodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.enablerNodeSelector }}
        {{- with .Values.api.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: port1
              containerPort: {{ .Values.api.service.ports.port1.containerPort }}
              protocol: {{ .Values.api.service.ports.port1.protocol }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          env:
            - name: CATALINA_OPTS
              value: -Ddb_host_name={{ include "db.fullname" . }} -Ddb_user={{ .Values.db.envVars.POSTGRES_USER}} -Ddb_password={{ .Values.db.envVars.POSTGRES_PASSWORD}} -Xms{{ .Values.api.catalina_ops.xms}} -Xmx{{ .Values.api.catalina_ops.xms}} {{ .Values.api.catalina_ops.debug}} -Djava.awt.headless=true -Dlogs.dir={{ .Values.api.catalina_ops.logs}} 
          livenessProbe:
            httpGet:
                path: /dashboard/dtos/list
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
