{{- if .Values.globalService }}
apiVersion: assist.eu/v1
kind: MultiClusterService
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    io.cilium/global-service: "true"
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  ports:
    - name: port1
      port: {{ .Values.web.service.ports.port1.port }}
      targetPort: {{ .Values.web.service.ports.port1.targetPort }}
      protocol: {{ .Values.web.service.ports.port1.protocol }}
{{- end }}